### ISSUE TITLE
"Pop!_OS here" link uses https: which, in Chrome, returns "Your connection is not private".

### ISSUE THREAD

**Issue by PatrickDGarvey** [system76/pop-docs#23]
The link is in the "Install Pop!_OS" document.

**Comment by WatchMkr** [comment]
Thanks for your bug report. Fixed!

**Comment by PatrickDGarvey** [comment]
I'm surprised you removed the https: security rather than make
pop.system76.com support https:

**Comment by WatchMkr** [comment]
The project to move pop docs to https is in the teams queue.

**Comment by PatrickDGarvey** [comment]
OK, great.

**Comment by wesinator** [comment]
http://pop.system76.com/docs/ now supports HTTPS but doesn't enforce or redirect to it automatically.

**Comment by cassidyjames** [comment]
@wesinator I've switched it to enforce and redirect to the HTTPS version now.
